<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>5a3d5d87-b3ca-46d5-8e3a-0ede4674c925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e48b1786-b95b-4938-bf37-f4f3f0395abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c955aaf0-a9d0-41ab-a25f-ca931b2d095b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spin</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>ebb8c1de-df34-4619-9d24-f346a53970c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>fbab4adf-c8de-44ed-bf18-46178d921043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOneWayFlight&quot;)/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row group-field shown&quot;]/div[@class=&quot;col-md-4 pr-0 ng-star-inserted&quot;]/div[@class=&quot;form-field float-label-wrapper populated&quot;]/div[@class=&quot;dropdown-menu passengers_flight_search_list ng-untouched ng-pristine ng-valid show&quot;]/div[@class=&quot;dropdown-option&quot;]/div[@class=&quot;spinner-wrap&quot;]/app-adult-child-infant-counter[1]/div[@class=&quot;spinner-input&quot;]/button[2]</value>
      <webElementGuid>62ee469c-d766-4098-9e1e-f41a17f3fb9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>db7c384f-0008-41ee-b72d-21194d996473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div[2]/div[2]/div/div[2]/div/div/app-adult-child-infant-counter/div/button[2]</value>
      <webElementGuid>d342a08d-14be-4d42-acac-0f98099256dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::button[1]</value>
      <webElementGuid>7454e1e3-cacc-4708-90d2-ac16d98625ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult'])[2]/following::button[2]</value>
      <webElementGuid>b358532a-16fd-4abe-966f-29faef7f41f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[2]/preceding::button[1]</value>
      <webElementGuid>f834346a-d3b2-473f-9c0f-391763929173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div[2]/div[2]/div/div[2]/div/div/app-adult-child-infant-counter/div/button[2]</value>
      <webElementGuid>c712455e-432c-4f91-8e8e-83563e2b72f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+' or . = '+')]</value>
      <webElementGuid>2f0d8e18-4f25-4a5d-a7aa-ea607efec7d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
