<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Allow</name>
   <tag></tag>
   <elementGuidId>f83e211a-39ef-4ade-9641-94872eb6e452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optInText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>919e58e9-1a23-44dc-acca-e6ff8eab268d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-id</name>
      <type>Main</type>
      <value>{{webPushPlatformData.chrome.domain_type == 'https' ? 'optInText': 'optInTextConventional'}}</value>
      <webElementGuid>2d975c6d-0dcc-4183-b238-05577d3fee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['allowButton']['color'],'background':webPushPreview['bannerv2']['web']['allowButton']['backgroundColor']}</value>
      <webElementGuid>74d6a889-df56-49e5-9ac7-de38b3cbd3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>641b410c-a7c5-4156-bb80-44ed7b4d6782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optInText</value>
      <webElementGuid>3f0cf773-c736-4c51-9a38-34c53dcb0a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow</value>
      <webElementGuid>85e68ff7-e016-4cb4-b1dd-707c0fd1712d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optInText&quot;)</value>
      <webElementGuid>3e431303-5a16-43a3-b4ef-1518acaf2195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='optInText']</value>
      <webElementGuid>5bc45e79-5b21-4e91-940b-06e82ccf7dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div/button[2]</value>
      <webElementGuid>2167e7ea-58c7-4042-b6a4-a65d69077e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't Allow')])[1]/following::button[1]</value>
      <webElementGuid>1d4a5327-11e8-4db5-9f19-0bd18cbe88aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jazeera Airways would like to send you awesome updates and offers!'])[1]/following::button[2]</value>
      <webElementGuid>cf6091d9-d178-4b23-b144-eadefee92c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::button[1]</value>
      <webElementGuid>7cf9c892-d3bb-4c5b-85e4-feef844ab19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR'])[1]/preceding::button[1]</value>
      <webElementGuid>ee21e3a5-3ced-4d82-919f-396ec1fad21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow']/parent::*</value>
      <webElementGuid>e751e618-2175-4155-b01b-6ff73ff08599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>eed9b9be-31ab-4610-9019-8e6072f09b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'optInText' and (text() = 'Allow' or . = 'Allow')]</value>
      <webElementGuid>e55a311a-a8db-46b7-b59e-a54f6d4a4fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Allow' or . = 'Allow')]</value>
      <webElementGuid>8fbd1608-286b-4ee2-af49-7f91d1854d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
