<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ -2</name>
   <tag></tag>
   <elementGuidId>109fc0fd-5371-46d4-8f9d-7e8aab23c987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Infant'])[2]/following::button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>596d898f-8d37-46fa-ab8d-c69cc4b49edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e953d836-db29-459f-b49a-835098d605d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spin</name>
      <type>Main</type>
      <value>up</value>
      <webElementGuid>34b50d7e-e6a0-4d3f-aead-1eac0d53ad2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>22fd4e2c-c591-4ec5-9e0e-1aaf3a00cc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOneWayFlight&quot;)/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row group-field shown&quot;]/div[@class=&quot;col-md-4 pr-0 ng-star-inserted&quot;]/div[@class=&quot;form-field float-label-wrapper populated&quot;]/div[@class=&quot;dropdown-menu passengers_flight_search_list ng-untouched ng-pristine ng-valid show&quot;]/div[@class=&quot;dropdown-option&quot;]/div[@class=&quot;spinner-wrap&quot;]/app-adult-child-infant-counter[1]/div[@class=&quot;spinner-input&quot;]/button[2]</value>
      <webElementGuid>32dfd4b7-262b-4de7-a060-43ca78346167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+' or . = '+')]</value>
      <webElementGuid>21fbd3d5-4bc1-4d8f-bccf-e1e65f4f8027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>c886dbde-9077-41b1-b523-0a2abe99fc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div[2]/div[2]/div/div[2]/div/div/app-adult-child-infant-counter/div/button[2]</value>
      <webElementGuid>ee1cb89e-9f02-4397-8818-da183450208b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::button[1]</value>
      <webElementGuid>44240367-cf67-4623-ad9e-3644e3e9430d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult'])[2]/following::button[2]</value>
      <webElementGuid>53034137-8935-4a30-a46a-93396e9e9faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[2]/preceding::button[1]</value>
      <webElementGuid>58ecf1bd-ba63-41d6-a4c4-bda2175f1c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div[2]/div[2]/div/div[2]/div/div/app-adult-child-infant-counter/div/button[2]</value>
      <webElementGuid>ca29cb05-8bdc-4e1f-85a8-eb05c0978c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
