<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_India_1_2_3</name>
   <tag></tag>
   <elementGuidId>26faa8b2-3019-49b2-8c43-657d4c680c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a05f770a7095-35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a05f770a7095-35']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d7e6004-9d78-4e27-b460-0939a6822f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>37180ee8-8716-47ca-974a-0f8820d93683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e3b208d6-6cef-4d13-856a-3dcd2677086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5bdcf17e-ee5d-4220-963f-91a7b5dd225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a05f770a7095-35</value>
      <webElementGuid>4bb895fe-24bb-4a1f-9915-f0a2494c1d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India</value>
      <webElementGuid>1d3a8d2a-5f42-4932-8bf9-4c10e628c54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a05f770a7095-35&quot;)</value>
      <webElementGuid>f4685ce7-975e-499e-88ec-ead0a07d4377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a05f770a7095-35']</value>
      <webElementGuid>5267f579-ee3c-48ad-8225-1a73b950a5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a05f770a7095']/div/div[2]/div</value>
      <webElementGuid>fb912b17-2032-4f47-80fa-0397bdb91481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[4]/following::div[11]</value>
      <webElementGuid>d30fe103-2ba1-4c2a-97e6-0aea79f794f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name'])[4]/following::div[13]</value>
      <webElementGuid>dcd66b35-8fcc-4005-a9c7-b4af87d9e7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::div[1]</value>
      <webElementGuid>23e5ed59-d929-4f4f-b658-ac9335b8cf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>e3cd4300-e9e2-4f16-b65a-9fa04cdb9476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a05f770a7095-35' and (text() = 'India' or . = 'India')]</value>
      <webElementGuid>212b82c5-2d13-4a9a-9bff-672f4176414e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
