<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mrs</name>
   <tag></tag>
   <elementGuidId>aed9839b-365b-417c-8e93-025e28e1835c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a7b540b173db-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a7b540b173db-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef17700f-f5fa-4e0e-9485-c0e2bd8f3e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>50e003eb-70b8-4d7e-8dec-6a9432bf6f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2f6eb004-5483-41fe-82cf-1f49fdeae58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4e0a7e8-3616-4894-a82e-7146ff74091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a7b540b173db-1</value>
      <webElementGuid>c1275e09-e335-4348-8ec4-3762e2c6cd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mrs</value>
      <webElementGuid>7e8f0f95-a931-4976-9a01-efea812924d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a7b540b173db-1&quot;)</value>
      <webElementGuid>01b8e913-6bd8-41e4-b99f-bb1f379c630c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a7b540b173db-1']</value>
      <webElementGuid>c24b8e3a-ab41-41c1-8552-9c4be1221904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a7b540b173db']/div/div[2]/div[2]</value>
      <webElementGuid>5309cd64-0ab6-4a96-b276-48579de38129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr'])[3]/following::div[1]</value>
      <webElementGuid>59c11469-0619-47e5-8682-e16640ef68c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr'])[2]/following::div[6]</value>
      <webElementGuid>07c37288-94cf-4d5f-8937-57a470cb5984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ms'])[1]/preceding::div[1]</value>
      <webElementGuid>7df5ac61-ec35-44dc-a029-580bd2be1bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>bc87a562-cc0a-444f-8331-08b3bcba93af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a7b540b173db-1' and (text() = 'Mrs' or . = 'Mrs')]</value>
      <webElementGuid>b885d864-2084-4fe2-a3ce-949dd91ce8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mrs' or . = 'Mrs')]</value>
      <webElementGuid>63031381-0090-496e-9dd0-682d71b41d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ac0cdeb9302d-1']</value>
      <webElementGuid>7b65f422-e733-4cf3-be60-009970ec776c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ac0cdeb9302d']/div/div[2]/div[2]</value>
      <webElementGuid>041285ae-fa76-4fda-b7d1-612d28fe57ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr'])[2]/following::div[1]</value>
      <webElementGuid>a2237e36-85ba-4602-a677-3afdef98625d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As written in passport'])[3]/following::div[17]</value>
      <webElementGuid>cb1fd614-094b-4f92-8dee-a270072a2e5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
