<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nationality_AdultDob</name>
   <tag></tag>
   <elementGuidId>8b7d5373-6241-48a6-a87b-0038448c77f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AdultDob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdultDob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0aec7ca-b0c9-4a5e-ad3d-8f05118d536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3600643-ce44-4c4c-a3d7-e570a8f49294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdultDob</value>
      <webElementGuid>7cbfb54d-3055-492b-8887-455075f3314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passengerDOB</value>
      <webElementGuid>eef126c2-b5a3-43fc-aee6-1ef5d702aa8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>696bfd7f-b01b-40f5-9480-8a70761f4139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker-dropdown ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>edd65d01-5a6e-4b4b-96b3-9985ed288d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>3dccef45-b196-46f8-8ccd-98f023a2f1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdultDob&quot;)</value>
      <webElementGuid>b434ce04-df06-4dd3-98d3-9ebc9d038ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdultDob']</value>
      <webElementGuid>ad40ce99-ecb4-43fa-9539-37bf246e9154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse0']/div/div/div[2]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>6c52b8f6-437a-45ff-b4ff-4bc36bb400fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>45a3cf40-cbdd-44ce-8b02-478fdf574308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AdultDob' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>c7ad07fe-6c1c-4bb5-957f-49c975942e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>694a1f02-f799-4156-a94a-0c096d344367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
