<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_to_flight_search</name>
   <tag></tag>
   <elementGuidId>f6f690cc-539c-4785-8a71-00782c5d28c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to_flight_searchsearchFlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='to_flight_searchsearchFlight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c64175c-e948-4c87-876c-17022c5f18a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to_flight_search</value>
      <webElementGuid>d09e96ae-7e0f-4ea1-92f3-c9a80dd8410d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beb9e1d1-7473-46c6-9fd9-d0e716f157f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>toPlace</value>
      <webElementGuid>f6c14be7-bc19-4ad6-bc2e-9d785b157763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>51b3be8a-cc90-413d-9bf6-fb8e67e2e899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8878c590-0c78-4b32-8001-d0dad4ad7e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-bold flight-search-input input-invert location-select place-hldr-color ng-untouched tt-input ng-dirty ng-valid</value>
      <webElementGuid>72f0c533-6e8b-47ba-b75e-f642e81f16f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to_flight_searchsearchFlight</value>
      <webElementGuid>355208dc-7cdf-4479-b7bb-f4b2f2e03b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To</value>
      <webElementGuid>20a82b63-82fd-4105-a3f1-212732aec125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>233cee80-46c7-4f6f-98ee-2c5209c8bb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8a8ddb52-8ae2-45e6-94bc-8586ae1f7317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to_flight_searchsearchFlight&quot;)</value>
      <webElementGuid>4f7b7a72-f704-4836-a676-bc1c5760ffbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to_flight_searchsearchFlight']</value>
      <webElementGuid>d1cc690e-e29e-42dc-9582-f5848c49f8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div/div[2]/div[2]/span[2]/input[2]</value>
      <webElementGuid>1ba2ec36-b4a2-44df-b9da-fd176611c012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span[2]/input[2]</value>
      <webElementGuid>0229e0d3-68f6-4cc3-9800-326500227e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'to_flight_search' and @type = 'text' and @id = 'to_flight_searchsearchFlight' and @placeholder = 'To']</value>
      <webElementGuid>7dfa42d1-b878-4ffd-9b48-a286f90bda85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='to_one_way_flight_searchsearchFlight']</value>
      <webElementGuid>06b97073-febf-4ba3-adea-1b1f5b29ef33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div[2]/div[2]/span[2]/input[2]</value>
      <webElementGuid>a9e662e9-5b8a-4a82-9090-c3af949d0b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'to_flight_search' and @type = 'text' and @id = 'to_one_way_flight_searchsearchFlight' and @placeholder = 'To']</value>
      <webElementGuid>6fc6c198-04c2-4a78-89f9-eed689c9b03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'to_flight_search' and @type = 'text' and @placeholder = 'To']</value>
      <webElementGuid>e21db3ad-2dff-4075-aa00-6eca4d345024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
