<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_titleLast1</name>
   <tag></tag>
   <elementGuidId>3e96ef22-4d5a-49c0-9d00-0e1dcde22529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleLast1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='titleLast1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b3bda55-a37b-4a68-b46c-922289af8f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode == 32) || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123)</value>
      <webElementGuid>4abd12c2-53d4-4f94-8fba-af392131d4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97dfda24-51aa-4fc5-960b-d3823ef1ea29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z\s]/g, ''),(/^[\u0621-\u064A\u0660-\u0669 ]+$/,'');</value>
      <webElementGuid>00664621-3140-431c-bc54-d14e635b4a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>7a527360-906a-4313-a0d8-e4330161c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>89ea9875-36a9-4106-9c08-3cdba1ec545d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8154b169-a67b-43d3-b0eb-160588b2cc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NcontactDetails1 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5b679f85-d4c5-4f74-bf7f-69d3cf12fc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleLast1</value>
      <webElementGuid>1cb8d282-165f-4e36-ba65-f3bcf4869a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name </value>
      <webElementGuid>9ae01b76-cd0a-4a99-b1aa-c28f6511581e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleLast1&quot;)</value>
      <webElementGuid>9af83660-b5f3-437f-82ff-d6155fa47f4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='titleLast1']</value>
      <webElementGuid>89c711e8-7982-4325-b96e-884a09fc12a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse1']/div/div/div[2]/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>17ab6488-8438-4e97-9fad-75bace4c99e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>f8fa5c25-b886-4ecb-937a-b6d14f46f664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'titleLast1' and @placeholder = 'Last Name ']</value>
      <webElementGuid>cabc479b-d32e-406a-b3f6-3f8329bd2885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
