<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KWD_checkbox-wrap primary</name>
   <tag></tag>
   <elementGuidId>326467f9-56fe-4052-b785-f6e92cf17f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.checkbox-wrap.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdefc50b-fff6-4d42-a48e-86863bebfff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>df55b65e-e963-42d7-b2cf-457cb1d6e611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-wrap primary</value>
      <webElementGuid>a25ee8e4-fc3f-4171-bd40-77f4372a1a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/app-root[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;router-container&quot;]/app-add-ons[@class=&quot;ng-star-inserted&quot;]/app-select-addons[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;btn-wrap center input_checkbox ng-star-inserted&quot;]/div[@class=&quot;cd_emailPromotions_div ng-star-inserted&quot;]/input[@class=&quot;checkbox-wrap primary&quot;]</value>
      <webElementGuid>cb85fa0e-1a3a-4832-8dac-b38e9fe6701e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>81ccac86-bf7f-4d0b-a3b0-dd46b87fd8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/input</value>
      <webElementGuid>644fef65-ae09-4449-8047-1483f65f23ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b794d5e4-1b69-4ec3-bf3b-9b7389c6cedc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
