<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nationality_InfantDob</name>
   <tag></tag>
   <elementGuidId>b3ec53ef-a5d3-459a-92f0-57c8bbc3b8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InfantDob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InfantDob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93683cd9-8313-49ba-8a46-be060976234f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d367957-2dbe-4e5c-84fe-64cba8ee4efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InfantDob</value>
      <webElementGuid>a870b785-8b93-4655-8518-c740b7859e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passengerDOB</value>
      <webElementGuid>fb0bec79-4ba9-47d2-8c20-c4dfc9161f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>733fef55-0813-4f13-8e0b-6428bf72dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker-dropdown ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b63181aa-9314-4e6c-8474-889068deb154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>d7d4c491-6151-40bb-b7fd-1863d6d6f6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InfantDob&quot;)</value>
      <webElementGuid>5551f1ca-93d7-410f-8971-45a2591ea8ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InfantDob']</value>
      <webElementGuid>9536c530-ea1a-4346-a4cf-acba28fd3d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse2']/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>ccfd856c-a493-4f38-9acd-4b9f4505af01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>95ba7c8d-9704-4273-99f7-2447efb3a666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InfantDob' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>f681cb74-bf8c-443d-a8b2-2447ccd8fbcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
