<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_from_flight_search</name>
   <tag></tag>
   <elementGuidId>56326a04-bdd4-4e6a-896d-ea6a3b866db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from_flight_searchsearchFlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from_flight_searchsearchFlight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bec86e56-2997-43ab-9bb0-6d3ec41d97e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>from_flight_search</value>
      <webElementGuid>63a63e34-7fbe-4607-83a1-90687d025365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8806bb1e-fda0-46e3-8460-2f10394d0d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fromPlace</value>
      <webElementGuid>c4cce45c-56a7-4032-a5c5-b0722ee8ea06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae0731ed-611d-4165-907d-86d1c5a8ea2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0b3cfce-6985-4f1d-b72e-bb9c446e0cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-bold flight-search-input input-invert location-select place-hldr-color ng-untouched ng-pristine ng-invalid tt-input</value>
      <webElementGuid>718e184b-33c3-4ca4-b541-7376eb86523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from_flight_searchsearchFlight</value>
      <webElementGuid>3106d8a2-f484-446e-8ff1-6de042932091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>08a10128-af49-48e6-9509-03b100fc8b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5389fcb4-619e-437f-b282-387421e730a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c4b62906-0ab8-4db3-9a18-70a45addfe08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from_flight_searchsearchFlight&quot;)</value>
      <webElementGuid>2674793d-921e-4599-8de5-a54e1f224a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from_flight_searchsearchFlight']</value>
      <webElementGuid>02ed38b2-6c7d-49a9-b4ec-837d4971639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchReturnFlight']/div/div/div/div[2]/span[2]/input[2]</value>
      <webElementGuid>62010ab3-fd64-4473-bdd5-a319488b6178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input[2]</value>
      <webElementGuid>a07ee874-4560-472f-bb38-6caf891a5822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'from_flight_search' and @type = 'text' and @id = 'from_flight_searchsearchFlight' and @placeholder = 'From']</value>
      <webElementGuid>5948c08b-60c0-40f9-904f-9b8107d8338d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
