<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_titleFirst1</name>
   <tag></tag>
   <elementGuidId>b000ade1-2d79-4724-b24d-9b70dfdf2fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleFirst1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='titleFirst1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e4af0da-10ba-4b80-af5e-f99fa93492f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z\s]/g, '');</value>
      <webElementGuid>971eb7b6-8d94-423c-a80f-6643421e0d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode == 32) || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123)</value>
      <webElementGuid>81bc4925-21bb-43c9-afd3-bca2143bf965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9edfee02-aa63-44c4-b41a-13177cb3d420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>c5af28f4-0ed6-4414-a0e3-754ffeec6c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>73c92e8d-227e-4053-b80b-3425670b6556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a428344-1aa5-4290-8da7-dda42cf621a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control1 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b5f88cc7-ad1f-4007-8b4f-9934bea2d6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleFirst1</value>
      <webElementGuid>a62df088-3fa0-43ff-83e3-a76ed9f30acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name </value>
      <webElementGuid>2b3543b5-df25-4941-a759-e8c6f98da4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleFirst1&quot;)</value>
      <webElementGuid>132d1991-a32e-4a66-ac08-4b64a3c08857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='titleFirst1']</value>
      <webElementGuid>44f00c28-6e61-4f38-b11a-176316fb44bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse1']/div/div/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>9403b126-3d5f-4083-984d-c5e166ac4b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>02c929df-bcf8-42aa-8f77-e69bffc3d507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'titleFirst1' and @placeholder = 'First name ']</value>
      <webElementGuid>99807a3e-a079-4b07-8d3c-8347e45fe0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
