<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_from_one_way_flight_searchsearchFlight</name>
   <tag></tag>
   <elementGuidId>1118ad0e-a6b4-4c9b-90bf-7ab96a0edafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from_one_way_flight_searchsearchFlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from_one_way_flight_searchsearchFlight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1157140-4bb3-460a-ad88-e0eafa1b6e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fromPlace</value>
      <webElementGuid>a1bd2a93-7990-4c73-9064-6bdfff6cca76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>676dc950-f341-47dc-9023-e72751ce3333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f1a605c-f38b-4dd3-affd-e6e2a55ee2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aaf00c0e-2ab0-4fc7-98b0-56ff91fa0f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control flight-search-input font-weight-bold input-invert location-select place-hldr-color ng-untouched ng-pristine ng-valid tt-input</value>
      <webElementGuid>e88ef702-9261-4cd3-95cb-29ff40ff92cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from_one_way_flight_searchsearchFlight</value>
      <webElementGuid>d6674b50-2732-47d5-9df2-f977b7179de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>f8bde751-27c6-4531-a90c-d66d5eeed3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fb68a01-e620-4e4b-8fee-8b59178eff42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c15bb49c-f92e-4f25-8e9c-29b6637eb891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from_one_way_flight_searchsearchFlight&quot;)</value>
      <webElementGuid>055c44dd-3108-4c4a-ba65-dc06d9327ded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from_one_way_flight_searchsearchFlight']</value>
      <webElementGuid>a8deff0e-e49f-4921-8a38-413a12c5618f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchOneWayFlight']/div/div/div/div[2]/span[2]/input[2]</value>
      <webElementGuid>d727db45-61c0-47ac-ad5c-a969d48103bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div/div/div[2]/span[2]/input[2]</value>
      <webElementGuid>f5098c81-85e1-4bc4-81ef-2ad32f6e56ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'from_one_way_flight_searchsearchFlight' and @placeholder = 'From']</value>
      <webElementGuid>6ebdb850-e48e-4acb-ac4a-65d32cc904f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'From']</value>
      <webElementGuid>9b89b948-7872-4a78-abe7-aeee4aba9166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
