<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_titleLast0</name>
   <tag></tag>
   <elementGuidId>0dea7575-ddd8-474e-8f37-14414464f8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleLast0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='titleLast0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c920bc94-664e-4295-ada0-fb3f3ebd48c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode == 32) || (event.charCode > 64 &amp;&amp; event.charCode &lt; 91) || (event.charCode > 96 &amp;&amp; event.charCode &lt; 123)</value>
      <webElementGuid>a319d4f4-6e89-433e-9515-7d453232c91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68c5fc06-7b88-46a8-92e2-ab6429f2bac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^A-Za-z\s]/g, ''),(/^[\u0621-\u064A\u0660-\u0669 ]+$/,'');</value>
      <webElementGuid>a4f9a457-9196-46e5-a888-d7e9f6a47d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>65e18787-db0f-43cc-a8e7-2b01e4f6895a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>8937e0e6-7402-4eaa-9f1c-0fe8b500384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7b0a0c5c-fa41-42e4-b820-1603225c5886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NcontactDetails0 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ebf0a60e-1258-43b1-937e-4681e0ad7872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleLast0</value>
      <webElementGuid>2a05e71a-70d1-41cf-aa7a-b3c70dde0bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name </value>
      <webElementGuid>c99e2eb3-97b8-4e65-b4e4-184787293864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleLast0&quot;)</value>
      <webElementGuid>8d1e7408-3b83-4e04-9a17-18739f3c4e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='titleLast0']</value>
      <webElementGuid>4615def2-699e-46b3-a26d-4ce71fcc8db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse0']/div/div/div[2]/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>91dc5e81-9925-4ea7-8e2c-037aa9738d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ca0adc6a-6093-4555-a197-26374e99d61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'titleLast0' and @placeholder = 'Last Name ']</value>
      <webElementGuid>00af27b4-ad2a-4f6f-95ac-71f0981ea14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/input</value>
      <webElementGuid>3a9e00d7-1cf0-4f73-af29-f145487e5872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Last Name ']</value>
      <webElementGuid>f00928e4-bfe5-41d2-bdf1-cdc8c9cbbdd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
