<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>e9626d8b-943e-4378-9214-df411eef5ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;flight-mockup-wrap economy-flight&quot;]/div[@class=&quot;flight-inside-wrap&quot;]/div[2]/div[@class=&quot;flight-select-seat-wrap economy-class-wrapper preffered ng-star-inserted&quot;]/div[@class=&quot;seat-row ng-star-inserted&quot;]/div[@class=&quot;seat-col right-col ng-star-inserted&quot;]/div[@class=&quot;checkbox-wrap ng-star-inserted&quot;]/label[1][count(. | //*[@data-original-title = concat(&quot;&lt;span class=&quot; , &quot;'&quot; , &quot;seat-num&quot; , &quot;'&quot; , &quot;>5B &lt;span class=&quot; , &quot;'&quot; , &quot;price&quot; , &quot;'&quot; , &quot;>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span>&quot;)]) = count(//*[@data-original-title = concat(&quot;&lt;span class=&quot; , &quot;'&quot; , &quot;seat-num&quot; , &quot;'&quot; , &quot;>5B &lt;span class=&quot; , &quot;'&quot; , &quot;price&quot; , &quot;'&quot; , &quot;>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span>&quot;)])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c09f27e4-5ada-4233-91bf-c1f2923be40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2a0bc69-9f2f-4ba7-b607-495274cfbc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>unit_SjkhMTIxISAhNjM4MzM5MDE2MDAwMDAwMDAwIUtXSSFEWEIhNUIhWQ--</value>
      <webElementGuid>bb63328b-f4ba-4790-8bb6-fd9630f01cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>&lt;span class='seat-num'>5B &lt;span class='price'>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span></value>
      <webElementGuid>180e1983-279c-4b75-8a4e-84a19017cff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip221472</value>
      <webElementGuid>46b30b62-4cb7-4d09-8f29-d691ab2e8700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;flight-mockup-wrap economy-flight&quot;]/div[@class=&quot;flight-inside-wrap&quot;]/div[2]/div[@class=&quot;flight-select-seat-wrap economy-class-wrapper preffered ng-star-inserted&quot;]/div[@class=&quot;seat-row ng-star-inserted&quot;]/div[@class=&quot;seat-col right-col ng-star-inserted&quot;]/div[@class=&quot;checkbox-wrap ng-star-inserted&quot;]/label[1]</value>
      <webElementGuid>f63226c5-dffa-4091-9696-585d4d34991d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/label</value>
      <webElementGuid>3e975465-c2c7-490f-8a58-041ec699e4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::label[26]</value>
      <webElementGuid>ecb7513b-eb7b-4197-8a83-1d2f21775c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::label[26]</value>
      <webElementGuid>65b473b2-c936-4d67-aa31-c87b53ddee87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[3]/preceding::label[143]</value>
      <webElementGuid>3a4df07d-02d3-4a2f-8e0f-a1847ba8bd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[2]/preceding::label[143]</value>
      <webElementGuid>c6d7199d-c1e0-40ab-986a-215c7d144c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/label</value>
      <webElementGuid>45ed012a-9984-4b00-9eee-162cad98164f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
