<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>e9626d8b-943e-4378-9214-df411eef5ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-original-title = concat(&quot;&lt;span class=&quot; , &quot;'&quot; , &quot;seat-num&quot; , &quot;'&quot; , &quot;>${seat} &lt;span class=&quot; , &quot;'&quot; , &quot;price&quot; , &quot;'&quot; , &quot;>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span>&quot;)]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>36ab38ff-fe92-4037-a2a1-dfd1d95131ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>919fd6ef-c8f5-4b4d-8b89-47c4c9f4e017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>unit_SjkhMTIxISAhNjM4MzM5MDE2MDAwMDAwMDAwIUtXSSFEWEIhNUIhWQ--</value>
      <webElementGuid>e33dfe02-0fa0-4f04-be2e-c751d7515af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>&lt;span class='seat-num'>${seat} &lt;span class='price'>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span></value>
      <webElementGuid>fb27eb7c-1671-4ac2-baac-bc3860d25dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip221472</value>
      <webElementGuid>ff308766-bf8e-4ece-821d-146605ce42eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;flight-mockup-wrap economy-flight&quot;]/div[@class=&quot;flight-inside-wrap&quot;]/div[2]/div[@class=&quot;flight-select-seat-wrap economy-class-wrapper preffered ng-star-inserted&quot;]/div[@class=&quot;seat-row ng-star-inserted&quot;]/div[@class=&quot;seat-col right-col ng-star-inserted&quot;]/div[@class=&quot;checkbox-wrap ng-star-inserted&quot;]/label[1]</value>
      <webElementGuid>b37c1c6f-0fd4-4b01-8eab-fe61175d77fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/label</value>
      <webElementGuid>88c4180e-a100-47c8-a2ab-5330cdd81616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::label[26]</value>
      <webElementGuid>f984801d-cd0d-419a-a4d2-2ea911f9e144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::label[26]</value>
      <webElementGuid>7d821415-1a24-415e-bc32-5ed1eb003b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[3]/preceding::label[143]</value>
      <webElementGuid>2ddb15c2-98af-45f0-8a8d-842499667ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[2]/preceding::label[143]</value>
      <webElementGuid>fb6005c0-bf1c-4ad6-986a-2aabf4d2ab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/label</value>
      <webElementGuid>1749049b-9202-4eb1-b70a-9103485a9327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
