<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_1</name>
   <tag></tag>
   <elementGuidId>b2d05a0e-b797-4b83-853e-4c62c14fe510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_2_container']/div/div/div[2]/div[2]/div[4]/div[3]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c78459b1-4f70-41c5-b6a3-0b79e3257905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>506dd7b0-1e8d-4945-bcc1-6422b6ed83af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>unit_SjkhMTI0ISAhNjM4MzQ1NDAzMDAwMDAwMDAwIURYQiFLV0khN0YhWQ--</value>
      <webElementGuid>3a8573d7-5e87-441e-9510-3b08e0bc7a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>&lt;span class='seat-num'>7F &lt;span class='price'>KWD &lt;strong> 7&lt;/strong>&lt;/span>&lt;/span></value>
      <webElementGuid>b56e3fbe-291e-4c54-a229-00e01c65f61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip565528</value>
      <webElementGuid>dcc45391-989d-44b8-adf6-420dc55a2ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_2_container&quot;)/div[@class=&quot;flight-mockup-wrap economy-flight&quot;]/div[@class=&quot;flight-inside-wrap&quot;]/div[2]/div[@class=&quot;flight-select-seat-wrap economy-class-wrapper preffered ng-star-inserted&quot;]/div[@class=&quot;seat-row ng-star-inserted&quot;]/div[@class=&quot;seat-col left-col ng-star-inserted&quot;]/div[@class=&quot;checkbox-wrap ng-star-inserted&quot;]/label[1]</value>
      <webElementGuid>e6f0242f-84bf-42b3-9306-c6af5f073949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_2_container']/div/div/div[2]/div[2]/div[4]/div[3]/div[3]/label</value>
      <webElementGuid>20081f20-203b-41d4-b164-3963a730202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[2]/following::label[42]</value>
      <webElementGuid>5d000830-37b4-402f-b341-60e784eb7be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::label[42]</value>
      <webElementGuid>b8711934-dc73-48c6-8147-8e2125c71f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[3]/preceding::label[127]</value>
      <webElementGuid>ae807121-0c2e-4ddc-958e-963b259cb9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[2]/preceding::label[127]</value>
      <webElementGuid>8aa1c848-9467-485f-aa4d-589977b18a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[3]/div[3]/label</value>
      <webElementGuid>0174aecf-346a-401c-ac2e-99e281d238a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
