<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Adult 1</name>
   <tag></tag>
   <elementGuidId>d5a8adf2-8f16-4ea2-bd0c-bcfb280dd47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.available-items > li.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passengerCollapse2']/div/div/div[2]/div/div/div/div/ngx-select-dropdown/div/div/ul[2]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>34972753-968b-48a9-8fe8-d56ae9d8cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>013ba45d-e754-423e-9d3a-15bebd6e5e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>c4c33f7c-aaf6-4ddd-9220-a18ecb9bbaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Adult 1 </value>
      <webElementGuid>f02a136d-fc2a-4a15-850d-4ac83735fbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengerCollapse2&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;panel-form-wrap cols__alignh-start&quot;]/div[@class=&quot;panel-form panelwidthadjust&quot;]/div[@class=&quot;form-wrap&quot;]/div[@class=&quot;form-row row ng-star-inserted&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;form-field float-label-wrapper travelmaxwidth&quot;]/ngx-select-dropdown[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ngx-dropdown-container&quot;]/div[@class=&quot;ngx-dropdown-list-container ng-star-inserted&quot;]/ul[@class=&quot;available-items&quot;]/li[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>f1c92c12-98e8-4806-bf5e-3655a0672ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengerCollapse2']/div/div/div[2]/div/div/div/div/ngx-select-dropdown/div/div/ul[2]/li</value>
      <webElementGuid>06bb0d60-d116-4c3f-8160-436a520e67af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travelling with'])[2]/following::li[1]</value>
      <webElementGuid>76259cba-29a3-46eb-aab3-5a1dba461bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travelling with'])[1]/following::li[1]</value>
      <webElementGuid>3d2c9c07-d020-4cce-b796-2d00e0bc3c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult 2'])[1]/preceding::li[1]</value>
      <webElementGuid>4c91b59a-fc41-4931-a7b2-d55644200f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[3]/preceding::li[2]</value>
      <webElementGuid>d61faef7-02cc-41bc-895d-ca2faf17d78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adult 1']/parent::*</value>
      <webElementGuid>5bf794e3-60f0-4b85-a491-9c29d2102b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li</value>
      <webElementGuid>f77ae192-1227-4c95-b0f5-56424506f8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Adult 1 ' or . = ' Adult 1 ')]</value>
      <webElementGuid>a7678a9f-3306-4de4-a7f9-3bb10e38f475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
