<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Passenger DetailsAs written in pass_f1c7d1</name>
   <tag></tag>
   <elementGuidId>f54cfe80-a222-4886-88ad-576257803b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passenger_details_section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='passenger_details_section']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>496fa563-54ee-41ae-a4e8-5d63a5c7dc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passenger_details_section</value>
      <webElementGuid>f4c7cdac-fe12-493c-94eb-f9907bafba0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>passenger-details-wrap tint-fill</value>
      <webElementGuid>7cea1b15-ecf9-4a2b-8b83-124738f85441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalojn User Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalojn User ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address</value>
      <webElementGuid>d33fb893-4567-4c20-94aa-9f4fc1a8ae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passenger_details_section&quot;)</value>
      <webElementGuid>bbe01229-3b73-4e0b-89f4-1d992ae6d365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='passenger_details_section']</value>
      <webElementGuid>271f592e-5ced-403b-bf7a-9857a6f56f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::section[1]</value>
      <webElementGuid>be3f0f32-2b7b-4a88-b730-5bb6a2f0e6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/section</value>
      <webElementGuid>c6e2cc63-7673-4303-a022-2997ffae8a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'passenger_details_section' and (text() = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalojn User Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalojn User ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address' or . = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalojn User Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalojn User ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address')]</value>
      <webElementGuid>cbed2e86-e906-430d-b98f-7f4c6a5e2286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'passenger_details_section' and (text() = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1Enter Passenger DetailsInfant1As written in passportTravelling withTravelling with ×TitleFirst name Last Name ×NationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name Country of residenceCityCodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address' or . = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1Enter Passenger DetailsInfant1As written in passportTravelling withTravelling with ×TitleFirst name Last Name ×NationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name Country of residenceCityCodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address')]</value>
      <webElementGuid>9bdc54ca-3de2-4834-8ea7-ea1d989b0f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1MSTR Katalon Test Infant1As written in passportTravelling withAdult 1 ×MasterTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name Country of residenceCityCodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address' or . = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1MSTR Katalon Test Infant1As written in passportTravelling withAdult 1 ×MasterTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name Country of residenceCityCodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address')]</value>
      <webElementGuid>848240ca-5e26-47c8-a4fa-5575a1cdf68e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
