<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Passenger DetailsAs written in pass_f1c7d1_1_2</name>
   <tag></tag>
   <elementGuidId>17c8c969-f342-4674-9aed-4193840f4d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passenger_details_section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='passenger_details_section']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>d17a237a-bfdf-470f-82cc-2204a00743b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passenger_details_section</value>
      <webElementGuid>ae98e993-c590-422e-a32b-84136272b217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>passenger-details-wrap tint-fill</value>
      <webElementGuid>ea704123-af2f-40ea-a329-5b100a4d9b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1MSTR Katalon Test Infant1As written in passportTravelling withAdult 1 ×MasterTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address</value>
      <webElementGuid>436e0bd8-6d27-4880-9105-92cb39a56f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passenger_details_section&quot;)</value>
      <webElementGuid>f1ac7a35-a38c-4f09-b1e9-0f6eafadc5ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='passenger_details_section']</value>
      <webElementGuid>1263a317-e812-4391-88e7-61cd1834e843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::section[1]</value>
      <webElementGuid>2d1096e3-7655-4803-81d4-34d8a446483d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/section</value>
      <webElementGuid>4cdb9723-3187-4de4-bfbe-820d4db48297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'passenger_details_section' and (text() = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1MSTR Katalon Test Infant1As written in passportTravelling withAdult 1 ×MasterTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address' or . = 'Passenger DetailsAs written in passportImportant NotePlease note that some countries will require visa to be valid for at least 6 months before the scheduled departure date. We advise you to check the visa regulations for your destination. Adult1MR Katalon Demo Primary ContactAdult1As written in passport×MrTitleFirst name Last Name ×IndiaNationalityDate of BirthAdult2MRS Katalon Demo Primary ContactAdult2As written in passport×MrsTitleFirst name Last Name ×IndiaNationalityDate of BirthInfant1MSTR Katalon Test Infant1As written in passportTravelling withAdult 1 ×MasterTitleFirst name Last Name ×IndiaNationalityDate of BirthContact DetailsPrimary Contact MR Katalon Demo ×MrTitleFirst name Last Name ×IndiaCountry of residenceCity+91CodeMobile NumberEmail AddressI would like to receive promotional emailsI would like to >Auto Check-InEmergency Contact Details OptionalAdd Emergency Contact DetailsEmergency Contact Details TitleFirst name Last Name Country of residenceCountry of residenceCodeMobile NumberEmail Address')]</value>
      <webElementGuid>932a7f07-a1eb-4976-9c54-ac117c54306b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
