<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_As written in passport_ng-arrow-wrapper_1</name>
   <tag></tag>
   <elementGuidId>7e251bab-be2e-4af8-bb80-764cc610397c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titleAdult1 > div.ng-select-container.ng-has-value > span.ng-arrow-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='titleAdult1']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b681f79d-0c11-4b07-bbde-66dc0c937734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>4cce2319-150a-43e7-834d-937ae483352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleAdult1&quot;)/div[@class=&quot;ng-select-container ng-has-value&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>d92bf1fc-6a6e-402b-8ea8-4e0156763428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='titleAdult1']/div/span</value>
      <webElementGuid>98fc317f-b79c-4d11-ba62-f947d2e7bb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As written in passport'])[3]/following::span[3]</value>
      <webElementGuid>09dde334-18bb-45d0-9f95-ed3e89f4d606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult2'])[2]/following::span[3]</value>
      <webElementGuid>9cf2ef86-48d8-4bc9-8b7c-02e26bdb84ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr'])[2]/preceding::span[2]</value>
      <webElementGuid>d201b66d-21ff-4811-ac6f-223be40cf407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mrs'])[1]/preceding::span[3]</value>
      <webElementGuid>d816f4b5-84e4-4fd2-a929-d79ae4f4b750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/ng-select/div/span</value>
      <webElementGuid>dcca043b-9637-47bd-9df0-3ccc5b474a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
