<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_october 2023</name>
   <tag></tag>
   <elementGuidId>6a68da65-783c-4beb-b2b2-cc106c0b027c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.month-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='departure_flight_date_range']/div/div/table/thead/tr/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>6d37ed58-2049-4ef0-8aa4-bd584c4163a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5816f592-57d4-4d38-856c-2bbb7e626262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>month-name</value>
      <webElementGuid>f4449ff7-b890-43ee-bb40-9fafc1830d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>october 2023</value>
      <webElementGuid>ec3fee1b-8236-49a1-af27-bea7cb9ec90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure_flight_date_range&quot;)/div[@class=&quot;date-picker-wrapper single-date no-shortcuts no-topbar inline-wrapper no-gap two-months&quot;]/div[@class=&quot;month-wrapper&quot;]/table[@class=&quot;month1&quot;]/thead[1]/tr[@class=&quot;caption&quot;]/th[@class=&quot;month-name&quot;]</value>
      <webElementGuid>45d55a11-b713-474f-8e34-6d1378a04264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='departure_flight_date_range']/div/div/table/thead/tr/th[2]</value>
      <webElementGuid>bec5b94c-e269-4c73-a1c1-7ea20c05d1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My-dates-are-flexible(-/+ 3 days)'])[1]/following::th[2]</value>
      <webElementGuid>c4e65d84-5578-47b0-b69d-d374263b8251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your departure date'])[2]/following::th[2]</value>
      <webElementGuid>07ee8118-6fe5-4ea9-ae74-7285028e368d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[1]/preceding::th[2]</value>
      <webElementGuid>d33ef6df-d132-452e-8ec6-34170c3d20da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>83c49007-c185-4439-9848-1d081fdd47fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'october 2023' or . = 'october 2023')]</value>
      <webElementGuid>0b0b81ce-41ee-46e2-92b0-bb00b625f7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='departure_flight_search_oneway_range_picker']/div/div/table[2]/thead/tr/th[2]</value>
      <webElementGuid>6379091a-6643-4da1-bee6-c13ab3d7c85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sat'])[5]/following::th[2]</value>
      <webElementGuid>c38b5b72-4788-4ba5-8cee-08e5421793ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fri'])[5]/following::th[3]</value>
      <webElementGuid>926f6b0a-5bdd-45cd-8e02-6a683cf2a84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sun'])[6]/preceding::th[2]</value>
      <webElementGuid>ad418ba0-87b2-411d-8459-9d385823510c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modify-search-one-way/div/form/div/div[2]/div/div/div[2]/div[3]/div/div/table[2]/thead/tr/th[2]</value>
      <webElementGuid>82e152c2-7b98-4158-a3bd-062fe7c0352e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
